<?php
require_once __DIR__ . '/auth.php'; require_admin(); require_once __DIR__ . '/../koneksi.php';
$rows=$conn->query("SELECT * FROM bookings ORDER BY tanggal DESC,jam DESC,id DESC");
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Booking | Haraka Admin</title><link rel="stylesheet" href="admin.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></head>
<body><aside class="side"><div class="brand"><i class="fas fa-scale-balanced"></i><span>HARAKA<br><small>ADMIN PANEL</small></span></div><a href="dashboard.php"><i class="fas fa-chart-pie"></i> Dashboard</a><a class="active" href="booking.php"><i class="fas fa-calendar-check"></i> Booking</a><a href="konsultasi.php"><i class="fas fa-comments"></i> Konsultasi</a><a href="../index.php"><i class="fas fa-globe"></i> Website</a><a href="logout.php"><i class="fas fa-right-from-bracket"></i> Logout</a></aside>
<main><header><div><span class="eyebrow">BOOKING MANAGEMENT</span><h1>Data Booking</h1><p>Kelola pengajuan jadwal konsultasi klien.</p></div></header>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Klien</th><th>Layanan</th><th>Jadwal</th><th>Metode</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php while($r=$rows->fetch_assoc()): ?><tr><td><b><?=htmlspecialchars($r['kode_booking'])?></b><br><small><?=htmlspecialchars($r['email'])?></small></td><td><?=htmlspecialchars($r['nama'])?><br><small><?=htmlspecialchars($r['no_whatsapp'])?></small></td><td><?=htmlspecialchars($r['layanan'])?></td><td><?=date('d/m/Y',strtotime($r['tanggal']))?><br><?=substr($r['jam'],0,5)?> WIB</td><td><?=htmlspecialchars($r['metode_konsultasi'])?></td><td><span class="badge <?=strtolower($r['status'])?>"><?=htmlspecialchars($r['status'])?></span></td><td><form method="POST" action="update_status.php" style="display:flex;gap:6px"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" style="background:#111;color:#fff;border:1px solid #333;padding:7px;border-radius:8px"><option <?=($r['status']=='Menunggu'?'selected':'')?>>Menunggu</option><option <?=($r['status']=='Dikonfirmasi'?'selected':'')?>>Dikonfirmasi</option><option <?=($r['status']=='Selesai'?'selected':'')?>>Selesai</option><option <?=($r['status']=='Dibatalkan'?'selected':'')?>>Dibatalkan</option></select><button class="gold-btn" style="border:0;cursor:pointer">Simpan</button></form></td></tr><?php endwhile; ?>
</tbody></table></div></section></main></body></html>
